$schema: "https://schemas.hackfed.org/v1/organization.json"
apiVersion: hackfed/v1
kind: Organization

metadata:
  orgId: bksp

spec:
  id: bksp
  name: B4CKSP4CE
  services:
    about:
      contact:
        website: https://bksp.in
        email: noc@bksp.in
    access:
      maintainers:
        - type: github
          username: heeeyflo
        - type: github
          username: radioegor146
        - type: github
          username: lordshatie
    wireguard:
      - address: fd79:7636:1f08:883d::008
        endpoint: lanskoe.loc.bksp.in:39242
        publicKey: AlF4my3ZX0ElrIOnRLiqbpYEucD3L03DrYIzoOYuGR8=
    telephony:
      exchanges:
        - id: primary
          protocol: iax2
          address: "[fd79:7636:1f08:883d::008]:4569"
          prefix: "+7509008"
          codecs: ["opus", "g722", "ulaw"]