$schema: "https://schemas.hackfed.org/v1/organization.json"
apiVersion: hackfed/v1
kind: Organization

metadata:
  orgId: fab20

spec:
  id: fab20
  name: FAB20
  services:
    about:
      contact:
        website: https://fab20.ee
        email: mail@rainwalker.ee
    access:
      maintainers:
        - type: github
          username: nan0desu
        - type: github
          username: fab20ee
        - type: github
          username: Lifemotion
        - type: github
          username: katerainwalker
    telephony:
      exchanges:
        - id: primary
          protocol: iax2
          address: "[fd79:7636:1f08:883d::009]:4569"
          prefix: "+7509009"
          codecs: ["opus", "g722", "ulaw"]