$schema: "https://schemas.hackfed.org/v1/organization.json"
apiVersion: hackfed/v1
kind: Organization

metadata:
  orgId: xecut

spec:
  id: xecut
  name: "Xecut"
  services:
    about:
      contact:
        website: https://xecut.me/
        email: hackspace@xecut.me
    access:
      maintainers:
        - type: github
          username: kirill9617
    wireguard:
      - address: fd79:7636:1f08:883d::381
        endpoint: ist.xecut.me:3469
        publicKey: oYOuRL8Xv+tW/qiq5f1Yz9YImg01YPmqY6B6VkCNlB8=
    telephony:
      exchanges:
        - id: primary
          protocol: iax2
          address: "[fd79:7636:1f08:883d::381]:4569"
          prefix: "+7509381"
          codecs: ["opus", "g722", "ulaw"]
