name: Check
on:
  # Run on pull requests to main branch
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2

      - name: Check Registry
        run: bunx @hackfed/toolbox@latest check-registry registry
