name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release Directories
    environment: Production
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Compile directories
        run: |
          mkdir -p dist
          bunx @hackfed/toolbox@latest generate-telephony --output dist/telephony.json registry
          bunx @hackfed/toolbox@latest generate-wireguard --output dist/wireguard.json registry

      - name: Set-up s5cmd
        uses: peak/action-setup-s5cmd@bde462e7399c68b4a9b05549d90b0e7d5c95e60f
        with:
          version: v2.3.0

      - name: Upload compiled directories
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          s5cmd --endpoint-url ${{ secrets.AWS_ENDPOINT_URL }} sync --delete 'dist/*.json' 's3://hackfed-directory/'
